### ISSUE TITLE
Reduce database file size after deleting items.

### ISSUE THREAD

**Issue by JohnShelley** [NorthArrowResearch/xsviewer-issues#18]
## The Problem
This is not a bug so much as functionality in the old version that is not in the new one as far as I can tell.

If I delete surveys from the data base, the data base size does not shrink.  I see no way to "clean up" the data base.

**Comment by JohnShelley** [comment]
As a plus, though, deleting a large survey is easily 10 times faster than it used to be.

**Comment by philipbaileynar** [comment]
Most database technologies do not automatically free up file space after deleting records. Performing this type of de-allocation within the Cross Section Viewer used to be (virtually) impossible back when we used Microsoft Access.

Fortunately, SQLite has a handy [Vacuum](https://www.sqlite.org/lang_vacuum.html) operation that can easily be called from within our code. The code just needs to be written carefully because it requires an exclusive connection to the database. In other words, no other users can be connected when this operation is performed. So I will implement it with a warning should it detect other users attached.

**Comment by philipbaileynar** [comment]
This is implemented for the next version.

Here's the [online help](http://xsviewer.northarrowresearch.com/Online_Help/File_Menu/compact_database.html)

![2018-08-31_114414](https://user-images.githubusercontent.com/8645379/44930462-3af63d00-ad13-11e8-8e27-c11822792552.png)

![2018-08-31_114356](https://user-images.githubusercontent.com/8645379/44930464-3cc00080-ad13-11e8-97b9-fb018cd7083a.png)
