### ISSUE TITLE
Long Profiles Not Updated

### ISSUE THREAD

**Issue by JohnShelley** [NorthArrowResearch/xsviewer-issues#7]
## The Problem

Deleting or creating long profiles under the Data menu does not show up in the Long Profile Viewer.

## Reproduction steps

1. Deleted the existing long profiles.
2. Created a new long profile.

## Exception message

The old profiles are still available in the Long Profile Viewer.  The new one is not.
The old profiles don't actually do anything when selected, but their names are still there.
If I completely close down the software and re-open, then the old profiles are gone and the new one is there.

**Comment by JohnShelley** [comment]
As a follow up: Here is a screen shot showing I created a new long profile.
![threelongprofiles](https://user-images.githubusercontent.com/41058803/42530712-654b1ee2-8471-11e8-8e22-d426e40d9d9b.png)


And here is another showing that the third long profile isn't in the list.

![onlytwolongprofiles](https://user-images.githubusercontent.com/41058803/42530717-69abc252-8471-11e8-987b-0996ec288765.png)

Live updating does not occur, not does it update if I close and reopen the specific tool.  If I close and reopen the entire program, then it appears.  @philipbaileynar

**Comment by philipbaileynar** [comment]
I have just encountered this myself inadvertently. The workflow is a little nuanced and somewhat counter intuitive. In the explanation below I reference the long profile example, but in reality this applies to every type of data in the system that the user can edit (surveys, group surveys etc).

If you have change (add, edit, delete) a long profile **while the long profile viewer tool is open** the change is properly reflected in the long profile viewer. However, if the long profile viewer is closed at the moment you change the long profile data then the long profile viewer does not reflect the change when it is opened.

This issue is resolved and will be part of the next release of the software (2.0.11).

**Comment by philipbaileynar** [comment]
This should be fixed in 2.0.11
