### ISSUE TITLE
Cross Section Viewer is throwing error message when being launched from GCD

### ISSUE THREAD

**Issue by joewheaton** [NorthArrowResearch/xsviewer-issues#9]
## The Problem

Watch the video... 

https://youtu.be/Tpz2xe0zNJ0
## Exception message

```text

test exception
 --- Exception Data --- 
Cross Section Viewer = 2.0.11.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 8/24/2018 8:36:55 AM
```

**Comment by joewheaton** [comment]
See [GCD Issue 313](https://github.com/Riverscapes/gcd/issues/313)

**Comment by philipbaileynar** [comment]
@joewheaton I suspect that you have an old release of the Cross Section Viewer. Or an unofficial internal beta release. There are no "test exception" messages in the current official release!

If you check for updates and get told that you have the latest version, then uninstall and re-install from scratch using the following link (because your current install might be pointing at a dead end testing ClickOnce deployment location that we used temporarily to work through the GCD/XSV linkage):

http://releases.northarrowresearch.com/XSViewer/setup.exe

**Comment by philipbaileynar** [comment]
I confess that I was wrong. There was indeed a legacy debugging exception in the code!. Fixed for next version.
